// Generated from holidays_detailed.yml
import { decodeHolidays } from './utils'

type HolidayName = [string, string]

const names: HolidayName[] = [
  ['元日', "New Year's Day"],
  ['成人の日', 'Coming of Age Day'],
  ['建国記念の日', 'National Foundation Day'],
  ['春分の日', 'Vernal Equinox Day'],
  ['天皇誕生日', "Emperor's Birthday"],
  ['憲法記念日', 'Constitution Memorial Day'],
  ['こどもの日', "Children's Day"],
  ['敬老の日', 'Respect for the Aged Day'],
  ['秋分の日', 'Autumnal Equinox Day'],
  ['体育の日', 'Health and Sports Day'],
  ['文化の日', 'National Culture Day'],
  ['勤労感謝の日', 'Labor Thanksgiving Day'],
  ['天皇誕生日 振替休日', 'Holiday in lieu'],
  ['秋分の日 振替休日', 'Holiday in lieu'],
  ['こどもの日 振替休日', 'Holiday in lieu'],
  ['敬老の日 振替休日', 'Holiday in lieu'],
  ['文化の日 振替休日', 'Holiday in lieu'],
  ['勤労感謝の日 振替休日', 'Holiday in lieu'],
  ['体育の日 振替休日', 'Holiday in lieu'],
  ['元日 振替休日', 'Holiday in lieu'],
  ['成人の日 振替休日', 'Holiday in lieu'],
  ['建国記念の日 振替休日', 'Holiday in lieu'],
  ['憲法記念日 振替休日', 'Holiday in lieu'],
  ['春分の日 振替休日', 'Holiday in lieu'],
  ['休日', "Citizen's Holiday"],
  ['大喪の礼', 'The Funeral Ceremony of Emperor Showa.'],
  ['みどりの日', 'Greenery Day'],
  ['みどりの日 振替休日', 'Holiday in lieu'],
  ['即位礼正殿の儀', 'The Ceremony of the Enthronement of His Majesty the Emperor (at the Seiden)'],
  ['結婚の儀', 'The Rite of Wedding of HIH Crown Prince Naruhito'],
  ['海の日', 'Marine Day'],
  ['海の日 振替休日', 'Holiday in lieu'],
  ['昭和の日', 'Showa Day'],
  ['昭和の日 振替休日', 'Holiday in lieu'],
  ['山の日', 'Mountain Day'],
  ['休日', 'Holiday'],
  ['休日（祝日扱い）', 'Holiday'],
  ['山の日 振替休日', 'Holiday in lieu'],
  ['体育の日（スポーツの日）', 'Health and Sports Day'],
  ['スポーツの日', 'Health and Sports Day'],
]
const holidays: number[] = decodeHolidays(
  'AAAOARsCJgMnBAQFAgaFBwgIEQkYChQLJwAOARsCJgMnBAQFAgaFBwkIEAkYChQLJwAOARsCJgMoBAQFAgaFBwgIEQkYChQLJwAOARsCJgMnBAEMAwUCBoUHCAgBDRAJGAoUCycADgEbAiYDJwQEBQIGAQ6EBwEPBwgRCRgKARATCycADgEbAiYDJwQEBQIGhQcJCBAJGAoUCwERJgAOARsCJgMoBAQFAgaFBwgIEQkBEhcKFAsnAA4BGwImAycEBAUCBoUHCAgRCRgKFAsnAAETDQEBFBoCJgMnBAQFAgaFBwgIEQkYChQLJwAOARsCARUlAycEAQwDBQIGhQcJCBAJGAoUCycADgEbAiYDKAQEBQIGhQcICBEJGAoUCwERJgAOARsCJgMnBAQFARYBBoUHCAgRCRgKFAsnAA4BGwImAwEXJgQEBQIGhQcICBEJARIXChQLJwAOARsCJgMnBAQFAgaFBwgIEQkYChQLJwABEw0BARQaAiYDKAQBDAMFAgaFBwgIAQ0QCRgKFAsnAA4BGwImAycEBAUCBgEOhAcBDwcIEQkYCgEQEwsnAA4BGwImAycEBAUCBoUHCAgRCRgKFAsBESYADgEbAiYDJwQEBQEWAQaFBwgIEQkYChQLJwAOARsCJgMBFycEBAUBGAEGhQcICBEJGAoUCycAARMNAQEUGgINGRkDJxoEBQEYAQaFBwgIEQkYChQLHgQJAA4BGwIBFSUDJxoBGwMFARgBBoUHCAgBDRAJGAoJHAsLHgQBDAgADgEbAiYDJxoEBQEYAQYBDoQHAQ8HCBEJGAoBEBMLHgQJAA4BGwImAygaBAUBFgEGhQcICBEJGAoUCx4ECQAOARsCJQMoGgQFARgBBiMdYgcICBEJARIXChQLHgQJAA4BGwImAycaBAUBGAEGhQcICBEJGAoUCx4ECQABEw0BARQaAiYDJxoEBQEYAQaFBwgIEQkYChQLHgQJAA4BGwIBFSUDKBoEBQEYAQYBDkseOQcBDwcIEQkYCgEQEwseBAkADgEbAiUDKBoEBQIGTB4BHzgHCAgRCRgKFAsBER0ECQAOARsCJgMnGgQFARYBBkweOQcICBEJGAoUCx4ECQAOARsCJgMBFyYaBAUBGAEGTB45BwgIEQkBEhcKFAseBAkACQEgAiYDKBoEBQEYAQZMHjkHCAgQCRkKFAseBAkABwEiAgEVJAMoGgEbAwUBGAEGTB45BwgIAQ0OCRoKFAseBAEMCAANARwCJgMnGgQFARgBBgEOSx45BwEPBwgVCRQKARATCx4ECQAMAR0CJgMnGgQFAgZNHjgHCAgUCRUKFAsBER0ECQALAR4CJgMoGgQFARgBBksePwcDCBIJFwoUCx4ECQAJASACJQMBFycaBAUBGAEGSh4/BwQIEQkYChQLHgQJAAETBwEhAiYDJxoEBQEYAQZJHj8HBQgQCRkKFAseBAkABwEiAgEVJQMnIAEhAwUBGgEGSB4/BwYIAQ0OCRoKFAseBAEMCAANARwCJgMoIAQFARoBBgEOTB44BwgIFAkVChQLAREdBAkACwEeAiUDKCAEBQEaAQYBDksePwcBGAEIEwkWChQLHgQJAAoBHwImAwEXJiAEBQEaAQZLHj8HAwgSCRcKFAseBAkACQEgAiYDJyAEBQEaAQZKHj8HBAgRCRgKFAseBAkAARMHASECJgMoIAEhAwUBGgEGSB4/BwUIEAkaChQLHgQBDAgADQEcAiUDKCAEBQEaAQYBDkYePwcHCBUJFAoBEBMLHgQJAAwBHQImAycgBAUBGgEGAQ5MHjgHCAgUCRUKFAsBER0ECQALAR4CJgMnIAQFARoBBgEOSx4/BwEYAQgTCRYKFAseBAkACgEfAiYDARcnIAQFARoBBkoeGCInBwMIEgkYChQLHgQJAAETBwEhAiUDKCAEBQEaAQZJHhkiJgcFCBAJGQoUCx4ECQAHASICARUlAycgASEDBQEaAQZIHhoiJQcGCAENDgkaChQLHgQBDAgADQEcAiYDJyABIwEkASMBBQEaAQYBDkYeGyIBJSMHBwgVJggkDAoBEBMLJwAMAR0CDAQBDBkDKCAEBQEaAQYBFk4eAScRIioHAQgqChQLJwAKAR8CDAQZAyggBAUBGgEGTh4BJxAiASUqBwMIKQoUCycACQEgAgwEGgMnIAQFARoBBkoeGCInBwQIEScYChQLJwABEwcBIQIMBBoDJyAEBQEaAQZJHhkiJgcFCBAnGQoUCycABwEiAgEVCwQaAyggBAUBGgEGAQ5GHhsiASUjBwYIAQ0VJxQKARATCycADAEdAgwEAQwYAyggBAUBGgEGAQ5MHhUiIwcICBQnFQoUCwERJgALAR4CDAQZAyggBAUBGgEGAQ5LHhYiKQcBGAEIEycWChQLJwAKAR8CDAQaAwEXJiAEBQEaAQZLHhciKAcDCBInFwoUCycACQEgAgwEGgMoIAQFARoBBkkeGSImBwQIEScZChQLJwAHASICARULBBkDKCABIQMFARoBBkgeGiIlBwYIAQ0OJxoKFAsnAA0BHAIMBBkDKCAEBQEaAQYBDkYeGyIBJSMHBwgVJxQKARATCycADAEdAgwEAQwZAycgBAUBGgEGAQ5MHhUiIwcICBQnFQoUCwERJgALAR4CDAQaAyggBAUBGgEGSx4XIigHARgBCBMnFwoUCycACQEgAgwEGQMBFycgBAUBGgEGSh4YIicHBAgRJxgKFAsnAAETBwEhAgwEGQMoIAQFARoBBkkeGSImBwUIECcZChQLJwAHASICARULBBoDJyABIQMFARoBBkgeGiIlBwYIAQ0OJxoKFAsnAA0BHAIMBBoDKCAEBQEaAQYBDkweFSIjBwcIFScVChQLAREmAAsBHgIMBBkDKCAEBQEaAQYBDkseFiIpBwEYAQgTJxYKFAsnAAoBHwIMBBkDKCAEBQEaAQZLHhciKAcDCBInFwoUCycACQEgAgwEGgMnIAQFARoBBkoeGCInBwQIEScYChQLJwABEwcBIQIMBBoDKCABIQMFARoBBkgeGiIlBwUIECcaChQLJwANARwCDAQZAyggBAUBGgEGAQ5GHhsiASUjBwcIFScUCgEQEwsnAAwBHQIMBAEMGAMoIAQFARoBBgEOTB4VIiMHCAgUJxUKFAsBESYACwEeAgwEGgMnIAQFARoBBgEOSx4WIikHARgBCBMnFgoUCycACgEfAgwEGgMBFycgBAUBGgEGSh4YIicHAwgSJxgKFAsnAAETBwEhAgwEGQMoIAQFARoBBkkeGSImBwQIEScZChQLJwAHASICARULBBkDKCABIQMFARoBBkgeGiIlBwYIAQ0OJxoKFAsnAA0BHAIMBBoDJyAEBQEaAQYBDkYeGyIBJSMHBwgVJxQKARATCycADAEdAgwEAQwZAyggBAUBGgEGAQ5LHhYiKQcBCBQnFgoUCycACgEfAgwEGQMoIAQFARoBBkseFyIoBwEYAQgTJxcKFAsnAAkBIAIMBBkDARcnIAQFARoBBkoeGCInBwQIEScYChQL',
)

export { names, holidays }
