// Generated from holidays_detailed.yml
import { decodeHolidays } from './utils'

type HolidayName = [string, string]

const names: HolidayName[] = [
  ['元日', "New Year's Day"],
  ['成人の日', 'Coming of Age Day'],
  ['建国記念の日', 'National Foundation Day'],
  ['春分の日', 'Vernal Equinox Day'],
  ['天皇誕生日', "Emperor's Birthday"],
  ['憲法記念日', 'Constitution Memorial Day'],
  ['こどもの日', "Children's Day"],
  ['敬老の日', 'Respect for the Aged Day'],
  ['秋分の日', 'Autumnal Equinox Day'],
  ['体育の日', 'Health and Sports Day'],
  ['文化の日', 'National Culture Day'],
  ['勤労感謝の日', 'Labor Thanksgiving Day'],
  ['天皇誕生日 振替休日', 'Holiday in lieu'],
  ['秋分の日 振替休日', 'Holiday in lieu'],
  ['こどもの日 振替休日', 'Holiday in lieu'],
  ['敬老の日 振替休日', 'Holiday in lieu'],
  ['文化の日 振替休日', 'Holiday in lieu'],
  ['勤労感謝の日 振替休日', 'Holiday in lieu'],
  ['体育の日 振替休日', 'Holiday in lieu'],
  ['元日 振替休日', 'Holiday in lieu'],
  ['成人の日 振替休日', 'Holiday in lieu'],
  ['建国記念の日 振替休日', 'Holiday in lieu'],
  ['憲法記念日 振替休日', 'Holiday in lieu'],
  ['春分の日 振替休日', 'Holiday in lieu'],
  ['休日', "Citizen's Holiday"],
  ['大喪の礼', 'The Funeral Ceremony of Emperor Showa.'],
  ['みどりの日', 'Greenery Day'],
  ['みどりの日 振替休日', 'Holiday in lieu'],
  ['即位礼正殿の儀', 'The Ceremony of the Enthronement of His Majesty the Emperor (at the Seiden)'],
  ['結婚の儀', 'The Rite of Wedding of HIH Crown Prince Naruhito'],
  ['海の日', 'Marine Day'],
  ['海の日 振替休日', 'Holiday in lieu'],
  ['昭和の日', 'Showa Day'],
  ['昭和の日 振替休日', 'Holiday in lieu'],
  ['山の日', 'Mountain Day'],
  ['休日', 'Holiday'],
  ['休日（祝日扱い）', 'Holiday'],
  ['山の日 振替休日', 'Holiday in lieu'],
  ['体育の日（スポーツの日）', 'Health and Sports Day'],
  ['スポーツの日', 'Health and Sports Day'],
]
const holidays: number[] = decodeHolidays(
  'AAAADgABKQACTwADdgAEegAFfAAGAQEHCQEIGgEJMgEKRgELbQEAewEBlgECvAED4wEE5wEF6QEGbgIHdwIIhwIJnwIKswIL2gIA6AIBAwMCKQMDUQMEVQMFVwMG3AMH5AMI9QMJDQQKIQQLSAQAVgQBcQQClwQDvgQEvwQMwgQFxAQGSQUHUQUIUgUNYgUJegUKjgULtQUAwwUB3gUCBAYDKwYELwYFMQYGMgYOtgYHtwYPvgYIzwYJ5wYK6AYQ+wYLIgcAMAcBSwcCcQcDmAcEnAcFngcGIwgHLAgIPAgJVAgKaAgLaQgRjwgAnQgBuAgC3ggDBgkECgkFDAkGkQkHmQkIqgkJqwkSwgkK1gkL/QkACwoBJgoCTAoDcwoEdwoFeQoG/goHBgsIFwsJLwsKQwsLagsAawsTeAsBeQsUkwsCuQsD4AsE5AsF5gsGawwHcwwIhAwJnAwKsAwL1wwA5QwBAA0CAQ0VJg0DTQ0ETg0MUQ0FUw0G2A0H4Q0I8Q0JCQ4KHQ4LRA4AUg4BbQ4Ckw4Duw4Evw4FwQ4GRg8HTg8IXw8Jdw8Kiw8LjA8Rsg8AwA8B2w8CARADKBAELBAFLRAWLhAGsxAHuxAIzBAJ5BAK+BALHxEALREBSBECbhEDbxEXlREEmREFmxEGIBIHKBIIORIJOhISURIKZRILjBIAmhIBtRIC2xIDAhMEBhMFCBMGjRMHlRMIphMJvhMK0hML+RMA+hMTBxQBCBQUIhQCSBQDcBQEcRQMdBQFdhQG+xQHAxUIBBUNFBUJLBUKQBULZxUAdRUBkBUCthUD3RUE4RUF4xUG5BUOaBYHaRYPcBYIgRYJmRYKmhYQrRYL1BYA4hYB/RYCIxcDShcEThcFUBcG1RcH3RcI7hcJBhgKGhgLGxgRQRgATxgBahgCkBgDtxgEuxgFvBgWvRgGQhkHShkIWxkJcxkKhxkLrhkAvBkB1xkC/RkD/hkXJRoEKRoFKhoYKxoGsBoHuBoIyRoJ4RoK9RoLHBsAHRsTKhsBKxsURRsCUhsZaxsDkhsalhsFlxsYmBsGHRwHJRwINhwJThwKYhwLgBwEiRwAlxwBshwCsxwV2BwD/xwaAB0bAx0FBB0YBR0Gih0Hkh0Ikx0Nox0Jux0KxB0czx0L7R0E7h0M9h0ABB4BHx4CRR4DbB4acB4FcR4Ych4Gcx4O9x4H+B4P/x4IEB8JKB8KKR8QPB8LWh8EYx8AcR8BjB8Csh8D2h8a3h8F3x8W4B8GZSAHbSAIfiAJliAKqiALyCAE0SAA3yAB+iACHyEDRyEaSyEFTCEYTSEGcCEd0iEH2iEI6yEJ7CESAyIKFyILNSIEPiIATCIBZyICjSIDtCIauCIFuSIYuiIGPyMHRyMIWCMJcCMKhCMLoiMEqyMArCMTuSMBuiMU1CMC+iMDISQaJSQFJiQYJyQGrCQHtCQIxSQJ3SQK8SQLDyUEGCUAJiUBQSUCQiUVZyUDjyUakyUFlCUYlSUGliUO4SUeGiYHGyYPIiYIMyYJSyYKTCYQXyYLfSYEhiYAlCYBryYC1CYD/CYaACcFAicGTiceTycfhycHjycIoCcJuCcKzCcLzScR6icE8ycAASgBHCgCQigDaSgabSgFbigWbygGuyge9CgH/CgIDSkJJSkKOSkLVykEYCkAbikBiSkCrykDsCkX1ika2ikF2ykY3CkGKCoeYSoHaSoIeioJeyoSkioKpioLxCoEzSoA1ioB9ioCHCsDRCsaSCsFSSsYSisGlisezysH1ysI5ysJACwKFCwLMiwEOywAQiwBZCwCZSwViSwDsSwasiwbtSwFtiwYtywGAy0ePC0HRC0IRS0NUy0JbS0KgS0Lny0EoC0MqC0AtS0B0S0C9y0DHi4aIi4FIy4YJC4GJS4OcC4eqS4Hqi4PsS4Ixi4J2i4K2y4Q7i4LDC8EFS8AIS8BPi8CZC8Diy8ajy8FkS8G3i8eFjAHHjAIMjAJRzAKWzALXDAReTAEgjAAjTABqzAC0TAD+TAa/TAF/jAY/zAGSjEeiTEHjDEInjEJtTEKyTEL5zEE8DEA+TEBGTICPjIDPzIXZjIaajIFazIYbDIGtjIe9TIH+TIICjMJIjMKNjMLVDMEXTMAXjMTZTMBhjMCrDMD0zMa1zMF2DMY2TMGIjQeYTQHZjQIdjQJjzQKozQLwTQEyjQA0TQB8zQC9DQVGTUDQDUgQTUhRDUFRTUaRjUGjjUezTUH0zUI1DUN4jUJ/DUKEDYLLjYELzYMNzYARDYBYDYChjYDrjYgsjYFszYatDYGtTYOATceOTcHQTcIVTcJajcKfjcLfzcRnDcEpTcAsDcBzjcC8zcDGzggHzgFIDgaITgGIjgObTgerDgHrTgYrjgIwTgJ1zgK6zgLCTkEEjkAHDkBOzkCYTkDYjkXiDkgjDkFjTkajjkG2TkeGDoHGzoILToJRDoKWDoLdjoEfzoAiDoBqDoCzjoD9Tog+ToF+joa+zoGRTsehDsHiDsImTsJsTsKxTsL4zsE7DsA7TsT9DsBFTwCOzwDYzwgZDwhZzwFaDwaaTwGsTwe8DwH9TwIBT0JHz0KMz0LUT0EUj0MWj0AZz0Bgz0CqD0D0D0g1D0F1T0a1j0G1z0OHT4eXD4HYz4IeD4JjD4KjT4QoD4Lvj4Exz4A0z4B8D4CFj8DPT8gQT8FQj8aQz8GRD8OkD8eyD8H0D8I5D8J+T8KDUALDkARK0AENEAAP0ABXUACg0ADqkAgrkAFr0AasEAGsUAO/EAeO0EHPEEYPUEIUEEJZkEKekELmEEEoUEAq0EBykEC8EED8UEXGEIgHEIFHUIaHkIGaEIegEIip0IHqkIIvEIJ1EIK6EILBkMED0MAEEMTF0MBOEMCXUMDhUMgiUMFikMai0MG1EMe7UMiE0QHGEQIKEQJQUQKVUQLc0QEfEQAg0QBpUQCpkQVy0QD8kQg80Qh9kQF90Qa+EQGQEUeWkUif0UHhUUIhkUNlEUJrkUKwkUL4EUE4UUM6UUA9kUBEkYCOEYDX0YgYEYjYUYkYkYjY0YFZEYaZUYGZkYOrEYex0YiyEYl60YH8kYIB0cmD0ckG0cKHEcQL0cLVkcAYkcBf0cCi0cEjEcMpUcDzUcg0UcF0kca00cG1EcWIkgeI0gnNEgiXkgHX0gIiUgKnUgLxEgAzkgB7UgC+UgEEkkDOkkgPkkFP0kaQEkGjkkej0knn0kioEklykkHzUkI9kkKCkoLMUoAOkoBWkoCZkoEgEoDp0ogq0oFrEoarUoG90oeD0siNksHOksIS0snY0sKd0sLnksAn0sTpksBx0sC00sE7UsDFEwgGEwFGUwaGkwGY0wefEwiokwHp0wIt0wn0EwK5EwLC00AEk0BNE0CNU0VQE0EWk0Dgk0ghk0Fh00aiE0GiU0Oz00e6k0i600lDk4HFE4IFU4NKk4nPk4KP04QUk4LeU4AhU4Bok4Crk4Er04Mx04D704g804F9E4a9U4G9k4OQk8eV08iek8Hgk8Ilk8nq08Kv08LwE8R5k8A8U8BD1ACG1AENFADXFAgYFAFYVAaYlAGY1AOrlAexFAi7VAH7lAY71AIAlEnGFEKLFELU1EAXVEBfFECiFEEolEDo1EXyVEgzVEFzlEaz1EGGlIeMVIiWVIHXFIIblInhVIKmVILwFIAyVIB6VIC9VIED1MDN1MgO1MFPFMaPVMGhlMen1MixVMHyVMI2lMn81MKB1QLLlQANVQBV1QCWFQVY1QEfFQDpFQgpVQhqFQFqVQaqlQG8lQeDFUiMVUHN1UIOFUNRlUnYFUKdFULm1UAqFUBxFUC0FUE6VUDEVYgFVYFFlYaF1YGGFYOXlYeeVYielYlnVYHpFYIuVYnzVYKzlYQ4VYLCFcAFFcBMVcCPVcEPlcMV1cDflcgglcFg1cahFcGhVcO0Vce5lciCVgHEVgIJVgnOlgKTlgLT1gRdVgAgFgBnlgCqlgExFgD7Fgg8FgF8Vga8lgGPVkeVFkifFkHfVkYflkIkVknqFkKvFkL41kA7FkBDFoCGFoEMVoDMloXWVogXVoFXloaX1oGqVoewVoi6FoH7FoI/VonFVsKKVsLUFsAUVsTWFsBeVsChVsEnlsDxlsgylsFy1sazFsGFVweLlwiVFwHWVwIaVwnglwKllwLvVwAxFwB5lwC51wV8lwEDF0DM10gNF0hN10FOF0aOV0GgV0em10iwF0Hxl0Ix10N1V0n710KA14LKl4AN14BU14CX14EeV4DoV4gpV4Fpl4ap14GqF4O9F4eCV8iLF8HM18ISF8nXV8KcV8Lcl8RmF8Ao18BwV8CzV8E5l8DDmAgEmAFE2AaFGAGFWAOYGAedmAin2AHoGAYoWAItGAnymAK3mALBWEAD2EBLmECOmEEU2EDe2Egf2EFgGEagWEGzGEe42EiC2IHDmIIIGInN2IKS2ILcmIAe2IBm2ICp2IEwWID6GIg7GIF7WIa7mIGOGMeUGMid2MHe2MIjGMnpGMKuGML32MA4GMT52MBCGQCFGQELmQDVmQgV2QhWmQFW2QaXGQGpGQevmQi42QH6GQI+GQnEmUKJmULTWUAWmUBdmUCgmUEm2UDw2Ugx2UFyGUayWUGymUOEGYeK2YiLGYlT2YHVmYIa2Ynf2YKgGYQk2YLumYAxmYB42YC72YE8GYMCGcDMGcgNGcFNWcaNmcGN2cOg2cemGciu2cHw2cI12cn7GcKAGgLAWgRJ2gAMmgBUGgCXGgEdmgDnWggoWgFomgao2gGpGgO72geBWkiLmkHL2kYMGkIQ2knWWkKbWkLlGkAnmkBvWkCyWkE42kD5GkXC2ogD2oFEGoaEWoGW2oec2oimmoHnWoIr2onx2oK22oLAmsAA2sTCmsBK2sCN2sEUGsDeGsgfGsFfWsafmsGx2se4GsiBmwHCmwIG2wnNGwKSGwLb2wAdmwBmGwCmWwVpGwEvWwD5Wwg5mwh6WwF6mwa62wGM20eTW0icm0HeG0IeW0Nh20noW0KtW0L3G0A6W0BBW4CEW4EK24DUm4gVm4FV24aWG4GWW4On24eum4iu24l3m4H5W4I+m4nDm8KD28QIm8LSW8AVW8Bcm8Cfm8Ef28MmG8DwG8gxG8FxW8axm8Gx28OEnAeKHAiUXAHUnAIZnAnfHAKkHALt3AAwXAB4HAC7HAEBXEDLXEgMXEFMnEaM3EGfnEelXEivXEHvnEYv3EI0nEn6XEK/XELJHIALXIBTXICWXIEcnIDc3IXmnIgnnIFn3IaoHIG6nIeAnMiKXMHLXMIPnMnVnMKanML',
)

export { names, holidays }
